//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUBGTweaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PUBGTweaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Core.System]
        ///Paths=../../../Engine/Content
        ///Paths=%GAMEDIR%Content
        ///Paths=../../../Engine/Plugins/OceanPlugin/Content
        ///Paths=../../../Engine/Plugins/Mutable/Content
        ///Paths=../../../Engine/Plugins/Runtime/Coherent/CoherentUIGTPlugin/Content
        ///Paths=../../../Engine/Plugins/RoadEditor/Content
        ///Paths=../../../Engine/Plugins/2D/Paper2D/Content
        ///Paths=../../../Engine/Plugins/Wwise/Content.
        /// </summary>
        internal static string Engine {
            get {
                return ResourceManager.GetString("Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [/Script/Engine.GameUserSettings]
        ///bUseDesiredScreenHeight=False
        ///
        ///[ScalabilityGroups]
        ///sg.ResolutionQuality=100.000000
        ///sg.ViewDistanceQuality=3
        ///sg.AntiAliasingQuality=3
        ///sg.ShadowQuality=1
        ///sg.PostProcessQuality=3
        ///sg.TextureQuality=3
        ///sg.EffectsQuality=1
        ///sg.FoliageQuality=0
        ///
        ///[/Script/TslGame.TslGameUserSettings]
        ///ScreenScale=120.000000
        ///Gamma=50.000000
        ///bIsLanMatch=True
        ///bIsMasterSoundMute=False
        ///MasterSoundVolume=100.000000
        ///bIsEffectSoundMute=False
        ///EffectSoundVolume=100.000000
        ///bIsUISoundMute=Fal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameUserSettings {
            get {
                return ResourceManager.GetString("GameUserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Scalability {
            get {
                return ResourceManager.GetString("Scalability", resourceCulture);
            }
        }
    }
}
